In [55]:
import pandas as pd

CEM_df_2017_H = pd.read_csv("./CEM_DATA_PREPROCESSED_2017_MAN_VICTIM.csv",delimiter=",")
CEM_df_2017_M = pd.read_csv("./CEM_DATA_PREPROCESSED_2017_WOMAN_VICTIM.csv",delimiter=",")
CEM_df_2018_H = pd.read_csv("./CEM_DATA_PREPROCESSED_2018_MAN_VICTIM.csv",delimiter=",")
CEM_df_2018_M = pd.read_csv("./CEM_DATA_PREPROCESSED_2018_WOMAN_VICTIM.csv",delimiter=",")
CEM_df_2019_H = pd.read_csv("./CEM_DATA_PREPROCESSED_2019_MAN_VICTIM.csv",delimiter=",")
CEM_df_2019_M = pd.read_csv("./CEM_DATA_PREPROCESSED_2019_WOMAN_VICTIM.csv",delimiter=",")
CEM_df_2020_H = pd.read_csv("./CEM_DATA_PREPROCESSED_2020_MAN_VICTIM.csv",delimiter=",")
CEM_df_2020_M = pd.read_csv("./CEM_DATA_PREPROCESSED_2020_WOMAN_VICTIM.csv",delimiter=",")

In [13]:
CEM_df_2020_M.columns

Index(['DEP', 'PROV', 'DISTR', 'FECHA_INGRESO', 'man_physical_v',
       'man_sexual_v', 'man_economical_v', 'man_psychological_v',
       'man_first_time', 'man_inf', 'man_nin', 'man_ado', 'man_ado_t',
       'man_jov', 'man_adu', 'man_m60', 'man_family', 'man_love', 'man_no_rel',
       'man_aggr_alcohol', 'man_aggr_drug', 'man_vict_disab', 'man_vict_alco',
       'man_vict_drug', 'man_vict_lgtbi', 'sex', 'WEEK'],
      dtype='object')

,DEP,PROV,DISTR,FECHA_INGRESO,man_physical_v,man_sexual_v,man_economical_v,man_psychological_v,man_first_time,man_inf,...,man_love,man_no_rel,man_aggr_alcohol,man_aggr_drug,man_vict_disab,man_vict_alco,man_vict_drug,man_vict_lgtbi,sex,WEEK
0,3.0,301,30101,01/02/2017,0,0,0,1,1,0,...,0,0,1,0,0,0,0,0,1,1
1,3.0,301,30101,01/12/2017,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,2
2,3.0,301,30101,03/09/2017,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,10
3,3.0,301,30101,03/09/2017,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,1,10
4,3.0,301,30101,05/03/2017,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14303,24.0,2403,240301,12/13/2017,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,1,50
14304,24.0,2403,240301,12/13/2017,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,1,50
14305,24.0,2403,240301,12/13/2017,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,1,50
14306,24.0,2403,240301,12/22/2017,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,51
14307,24.0,2403,240301,12/22/2017,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,1,51

In [56]:
def aggregate_for_day(base_df):
    print("comenzando")
    districts = base_df['DISTR'].unique()
    
    fecha =[]
    dep = []
    distr = []
    prov = []
    week = []
    
    physical_v = []
    sexual_v = []
    economical_v = []
    psychological_v = []
    first_time = []
    inf = []
    nin = []
    ado = []
    ado_t = []
    jov = []
    adu = []
    m60 = []
    family = []
    love = []
    no_rel = []
    aggr_alcohol = []
    aggr_drug =[]
    vict_disab = []
    vict_alco = []
    vict_drug = []
    vict_lgtbi = []
    
    for d in districts:
        
        partial_df = base_df[base_df['DISTR'] == d].reset_index(drop=True)
        dates = partial_df['FECHA_INGRESO'].unique()
        
        for j in range(len(dates)):
            physical_v_count = 0
            sexual_v_count = 0
            economical_v_count = 0
            psychological_v_count = 0
            first_time_count = 0
            inf_count = 0
            nin_count = 0
            ado_count = 0
            ado_t_count = 0
            jov_count = 0
            adu_count = 0
            m60_count = 0
            family_count = 0
            love_count = 0
            no_rel_count = 0
            aggr_alcohol_count = 0
            aggr_drug_count =0
            vict_disab_count = 0
            vict_alco_count = 0
            vict_drug_count = 0
            vict_lgtbi_count = 0
            
            first = True
            for i in range(len(partial_df['DISTR'])):
                if(partial_df['FECHA_INGRESO'][i] == dates[j]):
                    if(first):
                        dep.append(partial_df['DEP'][i])
                        distr.append(partial_df['DISTR'][i])
                        fecha.append(dates[j])
                        prov.append(partial_df['PROV'][i])
                        week.append(partial_df['WEEK'][i])
                        first = False
                        
                    physical_v_count += partial_df['man_physical_v'][i]
                    sexual_v_count += partial_df['man_sexual_v'][i]
                    economical_v_count += partial_df['man_economical_v'][i]
                    psychological_v_count += partial_df['man_psychological_v'][i]
                    first_time_count += partial_df['man_first_time'][i]
                    inf_count += partial_df['man_inf'][i]
                    nin_count += partial_df['man_nin'][i]
                    ado_count += partial_df['man_ado'][i]
                    ado_t_count += partial_df['man_ado_t'][i]
                    jov_count += partial_df['man_jov'][i]
                    adu_count += partial_df['man_adu'][i]
                    m60_count += partial_df['man_m60'][i]
                    family_count += partial_df['man_family'][i]
                    love_count += partial_df['man_love'][i]
                    no_rel_count += partial_df['man_no_rel'][i]
                    aggr_alcohol_count += partial_df['man_aggr_alcohol'][i]
                    aggr_drug_count += partial_df['man_aggr_drug'][i]
                    vict_disab_count += partial_df['man_vict_disab'][i]
                    vict_alco_count += partial_df['man_vict_alco'][i]
                    vict_drug_count += partial_df['man_vict_drug'][i]
                    vict_lgtbi_count += partial_df['man_vict_lgtbi'][i]

            physical_v.append(physical_v_count)
            sexual_v.append(sexual_v_count)
            economical_v.append(economical_v_count)
            psychological_v.append(psychological_v_count)
            first_time.append(first_time_count)
            inf.append(inf_count)
            nin.append(nin_count)
            ado.append(ado_count)
            ado_t.append(ado_t_count)
            jov.append(jov_count)
            adu.append(adu_count)
            m60.append(m60_count)
            family.append(family_count)
            love.append(love_count)
            no_rel.append(no_rel_count)
            aggr_alcohol.append(aggr_alcohol_count)
            aggr_drug.append(aggr_drug_count)
            vict_disab.append(vict_disab_count)
            vict_alco.append(vict_alco_count)
            vict_drug.append(vict_drug_count)
            vict_lgtbi.append(vict_lgtbi_count)
            
    #armamos df y retornamos
    data = {'fecha':fecha,'distr':distr, 'prov' : prov, 'dep':dep, 'week':week, 'physical_v':physical_v,
            'sexual_v':sexual_v, 'economical_v':economical_v, 'psychological_v':psychological_v, 'first_time':first_time,
            'inf':inf, 'nin':nin, 'ado':ado,'ado_t':ado_t,'jov':jov,'adu':adu,'m60':m60,'family':family,'love':love,
            'no_rel':no_rel,'aggr_alcohol':aggr_alcohol,'aggr_drug':aggr_drug,'vict_disab':vict_disab,'vict_alco':vict_alco,
            'vict_drug':vict_drug,'vict_lgtbi':vict_lgtbi}
    response_df = pd.DataFrame(data)
    print("acabado")
    return response_df

In [57]:
CEM_df_2017_H_DAYS = aggregate_for_day(CEM_df_2017_H)
CEM_df_2017_M_DAYS = aggregate_for_day(CEM_df_2017_M)
CEM_df_2018_H_DAYS = aggregate_for_day(CEM_df_2018_H)
CEM_df_2018_M_DAYS = aggregate_for_day(CEM_df_2018_M)
CEM_df_2019_H_DAYS = aggregate_for_day(CEM_df_2019_H)
CEM_df_2019_M_DAYS = aggregate_for_day(CEM_df_2019_M)
CEM_df_2020_H_DAYS = aggregate_for_day(CEM_df_2020_H)
CEM_df_2020_M_DAYS = aggregate_for_day(CEM_df_2020_M)

comenzando
acabado
comenzando
acabado
comenzando
acabado
comenzando
acabado
comenzando
acabado
comenzando
acabado
comenzando
acabado
comenzando
acabado

In [57]:
CEM_df_2019_M_DAYS

,fecha,distr,prov,dep,week,physical_v,sexual_v,economical_v,psychological_v,first_time,...,m60,family,love,no_rel,aggr_alcohol,aggr_drug,vict_disab,vict_alco,vict_drug,vict_lgtbi
0,06/06/2019,80301,803,8.0,127,3,0,0,1,0,...,1,1,2,1,1,0,0,0,0,0
1,01/02/2019,80301,803,8.0,105,2,0,0,1,0,...,0,0,3,0,2,0,0,0,0,0
2,01/04/2019,80301,803,8.0,105,0,0,0,2,0,...,0,0,2,0,2,0,0,0,0,0
3,01/07/2019,80301,803,8.0,106,0,0,0,2,0,...,1,1,1,0,0,0,0,0,0,0
4,01/08/2019,80301,803,8.0,106,2,0,0,2,1,...,0,2,2,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54718,12/17/2019,240301,2403,24.0,155,1,0,0,1,0,...,0,0,2,0,0,0,0,0,0,0
54719,12/18/2019,240301,2403,24.0,155,0,0,0,2,0,...,0,0,2,0,0,0,0,0,0,0
54720,12/20/2019,240301,2403,24.0,155,3,1,0,0,1,...,0,0,3,1,0,1,0,0,0,0
54721,12/30/2019,240301,2403,24.0,157,0,0,0,2,0,...,0,0,2,0,0,0,0,0,0,0
54722,12/31/2019,240301,2403,24.0,157,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [58]:
#verificamos fechas y distritos en ambos df

print("victimas hombre 2017 ")
print(" DISTR antes y despues ",len(CEM_df_2017_H['DISTR'].unique())," - ", len(CEM_df_2017_H_DAYS['distr'].unique()))
print(" FECHAS antes y despues ",len(CEM_df_2017_H['FECHA_INGRESO'].unique())," - ", len(CEM_df_2017_H_DAYS['fecha'].unique()))
print(" SEMANAS antes y despues ",len(CEM_df_2017_H['WEEK'].unique())," - ", len(CEM_df_2017_H_DAYS['week'].unique()))

print("victimas mujer 2017 ")
print(" DISTR antes y despues ",len(CEM_df_2017_M['DISTR'].unique())," - ", len(CEM_df_2017_M_DAYS['distr'].unique()))
print(" FECHAS antes y despues ",len(CEM_df_2017_M['FECHA_INGRESO'].unique())," - ", len(CEM_df_2017_M_DAYS['fecha'].unique()))
print(" SEMANAS antes y despues ",len(CEM_df_2017_M['WEEK'].unique())," - ", len(CEM_df_2017_M_DAYS['week'].unique()))

print("victimas hombre 2018 ")
print(" DISTR antes y despues ",len(CEM_df_2018_H['DISTR'].unique())," - ", len(CEM_df_2018_H_DAYS['distr'].unique()))
print(" FECHAS antes y despues ",len(CEM_df_2018_H['FECHA_INGRESO'].unique())," - ", len(CEM_df_2018_H_DAYS['fecha'].unique()))
print(" SEMANAS antes y despues ",len(CEM_df_2018_H['WEEK'].unique())," - ", len(CEM_df_2018_H_DAYS['week'].unique()))

print("victimas mujer 2018 ")
print(" DISTR antes y despues ",len(CEM_df_2018_M['DISTR'].unique())," - ", len(CEM_df_2018_M_DAYS['distr'].unique()))
print(" FECHAS antes y despues ",len(CEM_df_2018_M['FECHA_INGRESO'].unique())," - ", len(CEM_df_2018_M_DAYS['fecha'].unique()))
print(" SEMANAS antes y despues ",len(CEM_df_2018_M['WEEK'].unique())," - ", len(CEM_df_2018_M_DAYS['week'].unique()))

print("victimas hombre 2019 ")
print(" DISTR antes y despues ",len(CEM_df_2019_H['DISTR'].unique())," - ", len(CEM_df_2019_H_DAYS['distr'].unique()))
print(" FECHAS antes y despues ",len(CEM_df_2019_H['FECHA_INGRESO'].unique())," - ", len(CEM_df_2019_H_DAYS['fecha'].unique()))
print(" SEMANAS antes y despues ",len(CEM_df_2019_H['WEEK'].unique())," - ", len(CEM_df_2019_H_DAYS['week'].unique()))

print("victimas mujer 2019 ")
print(" DISTR antes y despues ",len(CEM_df_2019_M['DISTR'].unique())," - ", len(CEM_df_2019_M_DAYS['distr'].unique()))
print(" FECHAS antes y despues ",len(CEM_df_2019_M['FECHA_INGRESO'].unique())," - ", len(CEM_df_2019_M_DAYS['fecha'].unique()))
print(" SEMANAS antes y despues ",len(CEM_df_2019_M['WEEK'].unique())," - ", len(CEM_df_2019_M_DAYS['week'].unique()))

print("victimas hombre 2020 ")
print(" DISTR antes y despues ",len(CEM_df_2020_H['DISTR'].unique())," - ", len(CEM_df_2020_H_DAYS['distr'].unique()))
print(" FECHAS antes y despues ",len(CEM_df_2020_H['FECHA_INGRESO'].unique())," - ", len(CEM_df_2020_H_DAYS['fecha'].unique()))
print(" SEMANAS antes y despues ",len(CEM_df_2020_H['WEEK'].unique())," - ", len(CEM_df_2020_H_DAYS['week'].unique()))

print("victimas mujer 2020 ")
print(" DISTR antes y despues ",len(CEM_df_2020_M['DISTR'].unique())," - ", len(CEM_df_2020_M_DAYS['distr'].unique()))
print(" FECHAS antes y despues ",len(CEM_df_2020_M['FECHA_INGRESO'].unique())," - ", len(CEM_df_2020_M_DAYS['fecha'].unique()))
print(" SEMANAS antes y despues ",len(CEM_df_2020_M['WEEK'].unique())," - ", len(CEM_df_2020_M_DAYS['week'].unique()))

victimas hombre 2017
 DISTR antes y despues  262  -  262
 FECHAS antes y despues  363  -  363
 SEMANAS antes y despues  53  -  53
victimas mujer 2017
 DISTR antes y despues  264  -  264
 FECHAS antes y despues  365  -  365
 SEMANAS antes y despues  53  -  53
victimas hombre 2018
 DISTR antes y despues  285  -  285
 FECHAS antes y despues  365  -  365
 SEMANAS antes y despues  53  -  53
victimas mujer 2018
 DISTR antes y despues  289  -  289
 FECHAS antes y despues  365  -  365
 SEMANAS antes y despues  53  -  53
victimas hombre 2019
 DISTR antes y despues  311  -  311
 FECHAS antes y despues  365  -  365
 SEMANAS antes y despues  53  -  53
victimas mujer 2019
 DISTR antes y despues  312  -  312
 FECHAS antes y despues  365  -  365
 SEMANAS antes y despues  53  -  53
victimas hombre 2020
 DISTR antes y despues  315  -  315
 FECHAS antes y despues  260  -  260
 SEMANAS antes y despues  39  -  39
victimas mujer 2020
 DISTR antes y despues  318  -  318
 FECHAS antes y despues  263  -  263
 SEMANAS antes y despues  40  -  40

In [59]:
#CEM_df_2017_H_DAYS.to_csv('CEM_DATA_PREPROCESSED_2017_MAN_VICTIM_DAYS.csv', index = False)
#CEM_df_2017_M_DAYS.to_csv('CEM_DATA_PREPROCESSED_2017_WOMAN_VICTIM_DAYS.csv', index = False)
#CEM_df_2018_H_DAYS.to_csv('CEM_DATA_PREPROCESSED_2018_MAN_VICTIM_DAYS.csv', index = False)
#CEM_df_2018_M_DAYS.to_csv('CEM_DATA_PREPROCESSED_2018_WOMAN_VICTIM_DAYS.csv', index = False)
#CEM_df_2019_H_DAYS.to_csv('CEM_DATA_PREPROCESSED_2019_MAN_VICTIM_DAYS.csv', index = False)
#CEM_df_2019_M_DAYS.to_csv('CEM_DATA_PREPROCESSED_2019_WOMAN_VICTIM_DAYS.csv', index = False)
#CEM_df_2020_H_DAYS.to_csv('CEM_DATA_PREPROCESSED_2020_MAN_VICTIM_DAYS.csv', index = False)
#CEM_df_2020_M_DAYS.to_csv('CEM_DATA_PREPROCESSED_2020_WOMAN_VICTIM_DAYS.csv', index = False)

In [60]:
CEM_df_2017_H_DAYS = pd.read_csv("./CEM_DATA_PREPROCESSED_2017_MAN_VICTIM_DAYS.csv",delimiter=",")
CEM_df_2017_M_DAYS = pd.read_csv("./CEM_DATA_PREPROCESSED_2017_WOMAN_VICTIM_DAYS.csv",delimiter=",")
CEM_df_2018_H_DAYS = pd.read_csv("./CEM_DATA_PREPROCESSED_2018_MAN_VICTIM_DAYS.csv",delimiter=",")
CEM_df_2018_M_DAYS = pd.read_csv("./CEM_DATA_PREPROCESSED_2018_WOMAN_VICTIM_DAYS.csv",delimiter=",")
CEM_df_2019_H_DAYS = pd.read_csv("./CEM_DATA_PREPROCESSED_2019_MAN_VICTIM_DAYS.csv",delimiter=",")
CEM_df_2019_M_DAYS = pd.read_csv("./CEM_DATA_PREPROCESSED_2019_WOMAN_VICTIM_DAYS.csv",delimiter=",")
CEM_df_2020_H_DAYS = pd.read_csv("./CEM_DATA_PREPROCESSED_2020_MAN_VICTIM_DAYS.csv",delimiter=",")
CEM_df_2020_M_DAYS = pd.read_csv("./CEM_DATA_PREPROCESSED_2020_WOMAN_VICTIM_DAYS.csv",delimiter=",")

In [61]:
CEM_df_2018_H_DAYS

,fecha,distr,prov,dep,week,physical_v,sexual_v,economical_v,psychological_v,first_time,...,m60,family,love,no_rel,aggr_alcohol,aggr_drug,vict_disab,vict_alco,vict_drug,vict_lgtbi
0,02/14/2018,30101,301,3.0,59,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
1,02/22/2018,30101,301,3.0,60,0,0,0,2,0,...,0,2,0,0,0,0,0,0,0,0
2,03/06/2018,30101,301,3.0,62,0,0,0,1,0,...,0,1,0,0,1,0,0,0,0,0
3,04/30/2018,30101,301,3.0,70,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,06/15/2018,30101,301,3.0,76,0,0,0,2,0,...,0,2,0,0,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12286,12/10/2018,240301,2403,24.0,102,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
12287,12/14/2018,240301,2403,24.0,102,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
12288,12/17/2018,240301,2403,24.0,103,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
12289,12/18/2018,240301,2403,24.0,103,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
12290,12/28/2018,240301,2403,24.0,104,0,0,0,4,2,...,0,3,1,0,0,0,0,0,0,0

In [ ]:
#pasar los casos del 12/31/2017 al 2018 (semana 53)
#pasar los casos 12/30/2018 y 12/31/2018 asl 2019 (semana 105)
#pasar los casos del 12/29/2019 12/30/2019 y 12/31/2019 al 2020 (semana 157)

In [62]:
FROM_2017_TO_2018_H = CEM_df_2017_H_DAYS[CEM_df_2017_H_DAYS['week']==53]##.reset_index(drop=True)
FROM_2017_TO_2018_M = CEM_df_2017_M_DAYS[CEM_df_2017_M_DAYS['week']==53]##.reset_index(drop=True)

FROM_2018_TO_2019_H = CEM_df_2018_H_DAYS[CEM_df_2018_H_DAYS['week']==105]##.reset_index(drop=True)
FROM_2018_TO_2019_M = CEM_df_2018_M_DAYS[CEM_df_2018_M_DAYS['week']==105]##.reset_index(drop=True)

FROM_2019_TO_2020_H = CEM_df_2019_H_DAYS[CEM_df_2019_H_DAYS['week']==157]##.reset_index(drop=True)
FROM_2019_TO_2020_M = CEM_df_2019_M_DAYS[CEM_df_2019_M_DAYS['week']==157]##.reset_index(drop=True)

In [63]:
index_out_2017_H = FROM_2017_TO_2018_H.index
index_out_2017_M = FROM_2017_TO_2018_M.index

index_out_2018_H = FROM_2018_TO_2019_H.index
index_out_2018_M = FROM_2018_TO_2019_M.index

index_out_2019_H = FROM_2019_TO_2020_H.index
index_out_2019_M = FROM_2019_TO_2020_M.index

In [64]:
len(index_out_2018_H)

28

In [65]:
#retiro de filas

CEM_df_2017_H_DAYS = CEM_df_2017_H_DAYS.drop(CEM_df_2017_H_DAYS.index [ index_out_2017_H])
CEM_df_2017_M_DAYS = CEM_df_2017_M_DAYS.drop(CEM_df_2017_M_DAYS.index [ index_out_2017_M])

CEM_df_2018_H_DAYS = CEM_df_2018_H_DAYS.drop(CEM_df_2018_H_DAYS.index [ index_out_2018_H])
CEM_df_2018_M_DAYS = CEM_df_2018_M_DAYS.drop(CEM_df_2018_M_DAYS.index [ index_out_2018_M])

CEM_df_2019_H_DAYS = CEM_df_2019_H_DAYS.drop(CEM_df_2019_H_DAYS.index [ index_out_2019_H])
CEM_df_2019_M_DAYS = CEM_df_2019_M_DAYS.drop(CEM_df_2019_M_DAYS.index [ index_out_2019_M])

In [66]:
#Adición de filas
CEM_df_2018_H_DAYS = pd.concat([CEM_df_2018_H_DAYS,FROM_2017_TO_2018_H])
CEM_df_2018_M_DAYS = pd.concat([CEM_df_2018_M_DAYS,FROM_2017_TO_2018_M])

CEM_df_2019_H_DAYS = pd.concat([CEM_df_2019_H_DAYS,FROM_2018_TO_2019_H])
CEM_df_2019_M_DAYS = pd.concat([CEM_df_2019_M_DAYS,FROM_2018_TO_2019_M])

CEM_df_2020_H_DAYS = pd.concat([CEM_df_2020_H_DAYS,FROM_2019_TO_2020_H])
CEM_df_2020_M_DAYS = pd.concat([CEM_df_2020_M_DAYS,FROM_2019_TO_2020_M])

In [67]:
CEM_df_2017_H_DAYS = CEM_df_2017_H_DAYS.reset_index(drop=True)
CEM_df_2017_M_DAYS = CEM_df_2017_M_DAYS.reset_index(drop=True)

CEM_df_2018_H_DAYS = CEM_df_2018_H_DAYS.reset_index(drop=True)
CEM_df_2018_M_DAYS = CEM_df_2018_M_DAYS.reset_index(drop=True)

CEM_df_2019_H_DAYS = CEM_df_2019_H_DAYS.reset_index(drop=True)
CEM_df_2019_M_DAYS = CEM_df_2019_M_DAYS.reset_index(drop=True)

CEM_df_2020_H_DAYS = CEM_df_2020_H_DAYS.reset_index(drop=True)
CEM_df_2020_M_DAYS = CEM_df_2020_M_DAYS.reset_index(drop=True)

In [68]:
CEM_df_2018_H_DAYS

,fecha,distr,prov,dep,week,physical_v,sexual_v,economical_v,psychological_v,first_time,...,m60,family,love,no_rel,aggr_alcohol,aggr_drug,vict_disab,vict_alco,vict_drug,vict_lgtbi
0,02/14/2018,30101,301,3.0,59,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
1,02/22/2018,30101,301,3.0,60,0,0,0,2,0,...,0,2,0,0,0,0,0,0,0,0
2,03/06/2018,30101,301,3.0,62,0,0,0,1,0,...,0,1,0,0,1,0,0,0,0,0
3,04/30/2018,30101,301,3.0,70,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,06/15/2018,30101,301,3.0,76,0,0,0,2,0,...,0,2,0,0,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12261,12/18/2018,240301,2403,24.0,103,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
12262,12/28/2018,240301,2403,24.0,104,0,0,0,4,2,...,0,3,1,0,0,0,0,0,0,0
12263,12/31/2017,240101,2401,24.0,53,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
12264,12/31/2017,150117,1501,15.0,53,2,0,0,1,0,...,0,3,0,0,2,1,0,0,0,0
12265,12/31/2017,200601,2006,20.0,53,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0

In [69]:
#AGREGAMOS POR SEMANA
def aggregate_for_week(base_df):
    print("comenzando")
    districts = base_df['distr'].unique()
    
    fecha =[]
    dep = []
    distr = []
    prov = []
    week = []
    
    physical_v = []
    sexual_v = []
    economical_v = []
    psychological_v = []
    first_time = []
    inf = []
    nin = []
    ado = []
    ado_t = []
    jov = []
    adu = []
    m60 = []
    family = []
    love = []
    no_rel = []
    aggr_alcohol = []
    aggr_drug =[]
    vict_disab = []
    vict_alco = []
    vict_drug = []
    vict_lgtbi = []
    
    for d in districts:
        
        partial_df = base_df[base_df['distr'] == d].reset_index(drop=True)
        dates = partial_df['week'].unique()
        
        for j in range(len(dates)):
            physical_v_count = 0
            sexual_v_count = 0
            economical_v_count = 0
            psychological_v_count = 0
            first_time_count = 0
            inf_count = 0
            nin_count = 0
            ado_count = 0
            ado_t_count = 0
            jov_count = 0
            adu_count = 0
            m60_count = 0
            family_count = 0
            love_count = 0
            no_rel_count = 0
            aggr_alcohol_count = 0
            aggr_drug_count =0
            vict_disab_count = 0
            vict_alco_count = 0
            vict_drug_count = 0
            vict_lgtbi_count = 0
            
            first = True
            for i in range(len(partial_df['distr'])):
                if(partial_df['week'][i] == dates[j]):
                    if(first):
                        dep.append(partial_df['dep'][i])
                        distr.append(partial_df['distr'][i])
                        fecha.append(dates[j])
                        prov.append(partial_df['prov'][i])
                        week.append(partial_df['week'][i])
                        first = False
                        
                    physical_v_count += partial_df['physical_v'][i]
                    sexual_v_count += partial_df['sexual_v'][i]
                    economical_v_count += partial_df['economical_v'][i]
                    psychological_v_count += partial_df['psychological_v'][i]
                    first_time_count += partial_df['first_time'][i]
                    inf_count += partial_df['inf'][i]
                    nin_count += partial_df['nin'][i]
                    ado_count += partial_df['ado'][i]
                    ado_t_count += partial_df['ado_t'][i]
                    jov_count += partial_df['jov'][i]
                    adu_count += partial_df['adu'][i]
                    m60_count += partial_df['m60'][i]
                    family_count += partial_df['family'][i]
                    love_count += partial_df['love'][i]
                    no_rel_count += partial_df['no_rel'][i]
                    aggr_alcohol_count += partial_df['aggr_alcohol'][i]
                    aggr_drug_count += partial_df['aggr_drug'][i]
                    vict_disab_count += partial_df['vict_disab'][i]
                    vict_alco_count += partial_df['vict_alco'][i]
                    vict_drug_count += partial_df['vict_drug'][i]
                    vict_lgtbi_count += partial_df['vict_lgtbi'][i]

            physical_v.append(physical_v_count)
            sexual_v.append(sexual_v_count)
            economical_v.append(economical_v_count)
            psychological_v.append(psychological_v_count)
            first_time.append(first_time_count)
            inf.append(inf_count)
            nin.append(nin_count)
            ado.append(ado_count)
            ado_t.append(ado_t_count)
            jov.append(jov_count)
            adu.append(adu_count)
            m60.append(m60_count)
            family.append(family_count)
            love.append(love_count)
            no_rel.append(no_rel_count)
            aggr_alcohol.append(aggr_alcohol_count)
            aggr_drug.append(aggr_drug_count)
            vict_disab.append(vict_disab_count)
            vict_alco.append(vict_alco_count)
            vict_drug.append(vict_drug_count)
            vict_lgtbi.append(vict_lgtbi_count)
            
    #armamos df y retornamos
    data = {'fecha':fecha,'distr':distr, 'prov' : prov, 'dep':dep, 'week':week, 'physical_v':physical_v,
            'sexual_v':sexual_v, 'economical_v':economical_v, 'psychological_v':psychological_v, 'first_time':first_time,
            'inf':inf, 'nin':nin, 'ado':ado,'ado_t':ado_t,'jov':jov,'adu':adu,'m60':m60,'family':family,'love':love,
            'no_rel':no_rel,'aggr_alcohol':aggr_alcohol,'aggr_drug':aggr_drug,'vict_disab':vict_disab,'vict_alco':vict_alco,
            'vict_drug':vict_drug,'vict_lgtbi':vict_lgtbi}
    response_df = pd.DataFrame(data)
    print("acabado")
    return response_df

In [70]:
CEM_df_2017_H_WEEK = aggregate_for_week(CEM_df_2017_H_DAYS)
CEM_df_2017_M_WEEK = aggregate_for_week(CEM_df_2017_M_DAYS)
CEM_df_2018_H_WEEK = aggregate_for_week(CEM_df_2018_H_DAYS)
CEM_df_2018_M_WEEK = aggregate_for_week(CEM_df_2018_M_DAYS)
CEM_df_2019_H_WEEK = aggregate_for_week(CEM_df_2019_H_DAYS)
CEM_df_2019_M_WEEK = aggregate_for_week(CEM_df_2019_M_DAYS)
CEM_df_2020_H_WEEK = aggregate_for_week(CEM_df_2020_H_DAYS)
CEM_df_2020_M_WEEK = aggregate_for_week(CEM_df_2020_M_DAYS)

comenzando
acabado
comenzando
acabado
comenzando
acabado
comenzando
acabado
comenzando
acabado
comenzando
acabado
comenzando
acabado
comenzando
acabado

In [71]:
CEM_df_2017_H_WEEK.to_csv('CEM_DATA_PREPROCESSED_2017_MAN_VICTIM_WEEKS.csv', index = False)
CEM_df_2017_M_WEEK.to_csv('CEM_DATA_PREPROCESSED_2017_WOMAN_VICTIM_WEEKS.csv', index = False)
CEM_df_2018_H_WEEK.to_csv('CEM_DATA_PREPROCESSED_2018_MAN_VICTIM_WEEKS.csv', index = False)
CEM_df_2018_M_WEEK.to_csv('CEM_DATA_PREPROCESSED_2018_WOMAN_VICTIM_WEEKS.csv', index = False)
CEM_df_2019_H_WEEK.to_csv('CEM_DATA_PREPROCESSED_2019_MAN_VICTIM_WEEKS.csv', index = False)
CEM_df_2019_M_WEEK.to_csv('CEM_DATA_PREPROCESSED_2019_WOMAN_VICTIM_WEEKS.csv', index = False)
CEM_df_2020_H_WEEK.to_csv('CEM_DATA_PREPROCESSED_2020_MAN_VICTIM_WEEKS.csv', index = False)
CEM_df_2020_M_WEEK.to_csv('CEM_DATA_PREPROCESSED_2020_WOMAN_VICTIM_WEEKS.csv', index = False)